//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDichVu
    {
        public int ID_CTDV { get; set; }
        public Nullable<int> ID_HD { get; set; }
        public Nullable<int> ID_DV { get; set; }
    
        public virtual dichvu dichvu { get; set; }
        public virtual hoadon hoadon { get; set; }
    }
}
